const travelDestinations = [
  { id: 'abu-dhabi', label: 'Abu Dhabi', country: 'United Arab Emirates', latitude: 24.5, longitude: 54.4, precision: 'city', photos: ['abu_dhabi'], coverPhoto: 'abu_dhabi', status: 'ready' },
  { id: 'athens', label: 'Athens', country: 'Greece', latitude: 38.0, longitude: 23.7, precision: 'city', photos: ['athens', 'athens1', 'athens2'], coverPhoto: 'athens', status: 'ready' },
  { id: 'austin', label: 'Austin, Texas', country: 'United States', latitude: 30.3, longitude: -97.7, precision: 'city', photos: ['austin'], coverPhoto: 'austin', status: 'ready' },
  { id: 'bad-gastein', label: 'Bad Gastein', country: 'Austria', latitude: 47.1, longitude: 13.1, precision: 'city', photos: ['bad_gastien', 'bad_gastien2'], coverPhoto: 'bad_gastien', status: 'ready' },
  { id: 'bahamas', label: 'Bahamas', country: 'Bahamas', latitude: 24.3, longitude: -76.0, precision: 'country', photos: ['bahamas'], coverPhoto: 'bahamas', status: 'ready' },
  { id: 'canada', label: 'Canada', country: 'Canada', latitude: 56.1, longitude: -106.3, precision: 'country', photos: ['canada'], coverPhoto: 'canada', status: 'ready' },
  { id: 'china', label: 'China', country: 'China', latitude: 35.9, longitude: 104.2, precision: 'country', photos: ['china'], coverPhoto: 'china', status: 'ready' },
  { id: 'cordoba', label: 'Cordoba', country: 'Spain', latitude: 37.9, longitude: -4.8, precision: 'city', photos: ['cordoba', 'cordoba2', 'cordoba3'], coverPhoto: 'cordoba', status: 'ready' },
  { id: 'dubai', label: 'Dubai', country: 'United Arab Emirates', latitude: 25.2, longitude: 55.3, precision: 'city', photos: ['dubai', 'dubai2', 'dubai3'], coverPhoto: 'dubai', status: 'ready' },
  { id: 'ecuador', label: 'Ecuador', country: 'Ecuador', latitude: -1.8, longitude: -78.2, precision: 'country', photos: ['ecuador1', 'ecuador2'], coverPhoto: 'ecuador1', status: 'ready' },
  { id: 'florence', label: 'Florence', country: 'Italy', latitude: 43.8, longitude: 11.3, precision: 'city', photos: ['florence'], coverPhoto: 'florence', status: 'ready' },
  { id: 'georgia', label: 'Georgia', country: 'Georgia', latitude: 42.3, longitude: 43.4, precision: 'country', photos: ['georgia', 'georgi2', 'georgia3', 'georgia4', 'georgia5'], coverPhoto: 'georgia', status: 'needs_review' },
  { id: 'granada', label: 'Granada', country: 'Spain', latitude: 37.2, longitude: -3.6, precision: 'city', photos: ['granada', 'granada2', 'granada3', 'granada4', 'granada5', 'granada6', 'img_6079'], coverPhoto: 'granada', status: 'ready' },
  { id: 'great-wall', label: 'Great Wall', country: 'China', latitude: 40.4, longitude: 116.6, precision: 'landmark', photos: ['great_wall'], coverPhoto: 'great_wall', status: 'ready' },
  { id: 'hangzhou', label: 'Hangzhou', country: 'China', latitude: 30.3, longitude: 120.2, precision: 'city', photos: ['hangzhou'], coverPhoto: 'hangzhou', status: 'ready' },
  { id: 'jamaica', label: 'Jamaica', country: 'Jamaica', latitude: 18.1, longitude: -77.3, precision: 'country', photos: ['jamaica'], coverPhoto: 'jamaica', status: 'ready' },
  { id: 'lake-garda', label: 'Lake Garda', country: 'Italy', latitude: 45.6, longitude: 10.6, precision: 'region', photos: ['lakegarda'], coverPhoto: 'lakegarda', status: 'ready' },
  { id: 'los-angeles', label: 'Los Angeles area, California', country: 'United States', latitude: 34.1, longitude: -118.2, precision: 'region', photos: ['la', 'la2'], coverPhoto: 'la', status: 'needs_review' },
  { id: 'malaga', label: 'Malaga', country: 'Spain', latitude: 36.7, longitude: -4.4, precision: 'city', photos: ['malaga', 'malaga2'], coverPhoto: 'malaga', status: 'ready' },
  { id: 'mexico', label: 'Mexico', country: 'Mexico', latitude: 23.6, longitude: -102.6, precision: 'country', photos: ['mexico', 'mexico2'], coverPhoto: 'mexico', status: 'ready' },
  { id: 'milan', label: 'Milan', country: 'Italy', latitude: 45.5, longitude: 9.2, precision: 'city', photos: ['milan'], coverPhoto: 'milan', status: 'ready' },
  { id: 'munich', label: 'Munich', country: 'Germany', latitude: 48.1, longitude: 11.6, precision: 'city', photos: ['munich'], coverPhoto: 'munich', status: 'ready' },
  { id: 'muscat', label: 'Muscat', country: 'Oman', latitude: 23.6, longitude: 58.4, precision: 'city', photos: ['muscat', 'muscat2', 'muscat3'], coverPhoto: 'muscat', status: 'ready' },
  { id: 'ningbo', label: 'Ningbo', country: 'China', latitude: 29.9, longitude: 121.5, precision: 'city', photos: ['ningbo'], coverPhoto: 'ningbo', status: 'ready' },
  { id: 'north-carolina', label: 'North Carolina', country: 'United States', latitude: 35.8, longitude: -79.8, precision: 'region', photos: ['north_carolina'], coverPhoto: 'north_carolina', status: 'ready' },
  { id: 'pompeii', label: 'Pompeii', country: 'Italy', latitude: 40.7, longitude: 14.5, precision: 'landmark', photos: ['pompeii'], coverPhoto: 'pompeii', status: 'ready' },
  { id: 'rome', label: 'Rome', country: 'Italy', latitude: 41.9, longitude: 12.5, precision: 'city', photos: ['rome', 'rome2'], coverPhoto: 'rome', status: 'ready' },
  { id: 'salzburg', label: 'Salzburg', country: 'Austria', latitude: 47.8, longitude: 13.0, precision: 'city', photos: ['salzburg', 'salzburg2'], coverPhoto: 'salzburg', status: 'ready' },
  { id: 'seattle', label: 'Seattle, Washington', country: 'United States', latitude: 47.6, longitude: -122.3, precision: 'city', photos: ['seattle', 'seattle2', 'seattle3'], coverPhoto: 'seattle', status: 'ready' },
  { id: 'seville', label: 'Seville', country: 'Spain', latitude: 37.4, longitude: -6.0, precision: 'city', photos: ['seville', 'seville2'], coverPhoto: 'seville', status: 'ready' },
  { id: 'sri-lanka', label: 'Sri Lanka', country: 'Sri Lanka', latitude: 7.9, longitude: 80.8, precision: 'country', photos: ['sri_lanka', 'srilanka2', 'sri_lank3', 'sri_lank4'], coverPhoto: 'sri_lanka', status: 'ready' },
  { id: 'vienna', label: 'Vienna', country: 'Austria', latitude: 48.2, longitude: 16.4, precision: 'city', photos: ['vienna', 'vienna2'], coverPhoto: 'vienna', status: 'ready' },
  { id: 'washington', label: 'Washington, DC', country: 'United States', latitude: 38.9, longitude: -77.0, precision: 'city', photos: ['dc'], coverPhoto: 'dc', status: 'ready' }
].map(destination => ({
  ...destination,
  photos: destination.photos.map(photo => `img/travel-web/${photo}.jpg`),
  coverPhoto: `img/travel-web/${destination.coverPhoto}.jpg`
}));